version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/back-end
permissions:
  - object: /home/ubuntu/back-end
    owner: ubuntu
    group: ubuntu
    mode: 755
    
hooks:
  AfterInstall:
    - location: /home/ubuntu/back-end
      timeout: 400
      runas: ubuntu
      commands:
        - scripts/deploy.sh
