version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/back-end
permissions:
  - object: /home/ubuntu/back-end
    owner: ubuntu
    group: ubuntu
    mode: 755
    
hooks:
  AfterInstall:
    - location: scripts/
      timeout: 400
      runas: ubuntu
      commands:
        - sh deploy.sh   
# hooks:
#   AfterInstall:
#     - location: scripts/deploy.sh
#       timeout: 400
#       runas: ubuntu
#       commands:
#         - chmod +x scripts/deploy.sh
#         - sh scripts/deploy.sh
